### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by Raiondesu** [Raiondesu/intl-schematic#2]
This is an issue to track my main points of improving this library for public use that are in progress right now, in no particular order:

- [x] Decouple plugins architecturally from the core library
- [x] [Publish `@intl-schematic/solid`](https://www.npmjs.com/package/@intl-schematic/solid)
    - [x] Integrate with JSX
- [x] [Comprehensive docs for the core library](../tree/HEAD/packages/core/)
- [x] Move plugins into separate packages
  - [`@intl-schematic/plugin-defaults`](../tree/HEAD/packages/plugins/defaults/)
    - recommended collection of plugins that should be useful to most applications
  - [`@intl-schematic/plugin-arrays`](../tree/HEAD/packages/plugins/arrays/) (included in **defaults**)
    - use arrays to cross-reference keys and define complex multiline texts
  - [`@intl-schematic/plugin-functions`](../tree/HEAD/packages/plugins/functions/)
    - use plain functions directly in translation documents with type-checked parameters
  - [`@intl-schematic/plugin-locale`](../tree/HEAD/packages/plugins/locale/) (included in **defaults**)
    - provider plugin, allows other plugins to use the provided `Intl.Locale` instance
  - [`@intl-schematic/plugin-nested`](../tree/HEAD/packages/plugins/nested/)
    - access nested keys in deep multi-level objects
  - [`@intl-schematic/plugin-processors`](../tree/HEAD/packages/plugins/processors/) (included in **defaults**)
    - apply custom and default processors to format the user inputs
- [x] [Comprehensive documentation for plugins API](../tree/HEAD/packages/plugins/)
- [x] JSON-schemas for all suitable packages
- [x] JSON-schema docs for core library
- [ ] JSON-schema docs for plugins
- [ ] A separate documentation website
- [ ] Add adapters for other front-end frameworks
  - [ ] [`@intl-schematic/vue`](../tree/HEAD/packages/vue/)
    - [ ] Integrate with the template system
  - [ ] [`@intl-schematic/react`](../tree/HEAD/packages/react)
    - [ ] Integrate with JSX
  - [ ] `@intl-schematic/astro`
    - [ ] Integrate with components
- [ ] Extend plugins API
  - [ ] Add ability to pre- and post-process the translation (maybe not needed due to functional design?)
  - [ ] Allow [`match`](https://github.com/Raiondesu/intl-schematic/blob/2ac8782460455bbb31cd81030c92615cd11ac2e1/packages/core/src/plugins.ts#L95) to type-guard keys
  - [ ] Allow plugin overrides when translating, in case there's a collision in multiple plugins' `match` checks on a single key.
- [ ] [Project/schema initializer cli](../tree/HEAD/packages/cli)
  - [ ] Initialize translation documents in accordance with plugins and schemas
  - [ ] Initialize JSON-schemas
  - [ ] Check for inconsistencies/desync in translation documents
  - [ ] Validate translation documents against used plugins, not just JSON-schemas
  - [ ] Automatically configure JSON-schemas for the user's IDE
- [ ] Type helper for quickly asserting variable to some of `t`'s parameters type 
- [ ] Add smart caching for plugin-key relations

**Comment by Raiondesu** [comment]
Man, I really need help if I want to integrate this into other frameworks...
